name: Test action

on:
    push:
        branches: [main]
    # Remove the line above to run when pushing to master or main
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test action
        runs-on: ubuntu-latest

        services:
            mysql:
              image: mysql:8.0
              env:
                MYSQL_ROOT_PASSWORD: root
              ports:
                - "8888:3306"
              options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v3

            - uses: ./
